export enum EmailTemplateType {
  ADMIN_SIGNUP_OTP = 'ADMIN_SIGNUP_OTP',
  ADMIN_FORGOT_PASSWORD = 'ADMIN_FORGOT_PASSWORD',
  ADMIN_RESET_PASSWORD = 'ADMIN_RESET_PASSWORD',
  USER_SIGNUP_OTP = 'USER_SIGNUP_OTP',
  USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD',
  USER_RESET_PASSWORD = 'USER_RESET_PASSWORD',
  USER_WELCOME = 'USER_WELCOME',
  ADMIN_WELCOME = 'ADMIN_WELCOME',
}

